name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/parser-tg-bot

            git pull origin main

            docker compose up -d --build --remove-orphans

            docker image prune -f
